import { part1, part2 } from "./solution";

const input = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

test("d8p1", () => {
  expect(part1(input)).toBe(14)
});

test("d8p2", () => {
  expect(part2(input)).toBe(34)
});